"""Generates payloads/cover5mib.bin: one 5 MiB multipart/form-data body.

The upload scenario is the only one where request-body handling dominates, so
the payload is a complete wire-format body rather than something the load
generator assembles: the generator sends bytes verbatim, and a body built once
here is byte-identical for all five implementations.

The boundary is fixed and committed so the harness can send a matching
Content-Type without parsing the file. The file part is exactly 5 MiB, which
the contract accepts (the limit is 10 MiB), so every implementation takes the
success path and the peak-RSS column measures buffering rather than rejection.

Bytes are drawn from a fixed PRNG seed: incompressible enough that nothing can
win by collapsing a run of zeroes, and identical on every run.
"""

from __future__ import annotations

import random
from pathlib import Path

BOUNDARY = "apibenchcover9f2c41d7e6b3"
FILE_BYTES = 5 * 1024 * 1024


def main() -> None:
    payload = random.Random(0x5C0FFEE).randbytes(FILE_BYTES)
    # JPEG start-of-image, so the part is not merely plausible by its header.
    payload = b"\xff\xd8\xff\xe0" + payload[4:]

    marker = f"--{BOUNDARY}".encode("ascii")
    if marker in payload:
        raise SystemExit("generated bytes contain the boundary; change the seed")

    head = (
        f"--{BOUNDARY}\r\n"
        'Content-Disposition: form-data; name="file"; filename="cover.jpg"\r\n'
        "Content-Type: image/jpeg\r\n"
        "\r\n"
    ).encode("ascii")
    tail = f"\r\n--{BOUNDARY}--\r\n".encode("ascii")

    target = Path(__file__).resolve().parent.parent / "payloads" / "cover5mib.bin"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(head + payload + tail)
    print(
        f"wrote {target}: {target.stat().st_size} bytes total, "
        f"{FILE_BYTES} in the file part, boundary {BOUNDARY}"
    )


if __name__ == "__main__":
    main()
